In [1]:
import pandas as pd
import numpy as np

## Data Clean and Concat

In [23]:
first = pd.read_csv('../data/combined/FIRST_WISE_SDSS_DR12.csv')
spies = pd.read_csv('../data/combined/SpIES_WISE_SDSS_DR12.csv')

In [24]:
first['data'] = 'FIRST'
spies['data'] = 'SpIES'

In [30]:
first_c = first.drop(columns = ['errHalfMaj',
       'errHalfMin', 'errPosAng','errHalfMaj_x', 'errHalfMin_x', 'errPosAng_x',
                      'e_umag','e_gmag','e_rmag','e_imag','e_zmag','e_zsp', 'e_zph',
                     'e_pmRA','e_pmDE','RAdeg', 'DEdeg'])

spies_c = spies.drop(columns = ['ra_x',
       'dec_x', 'errHalfMaj', 'errHalfMin', 'errPosAng','e_W1mag', 'e_W2mag',
       'e_W3mag', 'e_W4mag', 'e_Jmag', 'e_Hmag', 'e_Kmag','RAdeg', 'DEdeg',
       'errHalfMaj_x', 'errHalfMin_x', 'errPosAng_x', 'e_umag','e_gmag','e_rmag','e_imag','e_zmag','e_zsp', 'e_zph',
                     'e_pmRA','e_pmDE','W1mag', 'W2mag'])

In [31]:
first_c.rename(columns ={'ra_u':'RA','dec_u':'DEC','Jmag':'J_mag','Kmag':'K_mag','Class':'class'},inplace = True)

In [32]:
spies_c.rename(columns = {'G_MAG_AB':'G_mag','R_MAG_AB':'R_mag', 'Y_MAG_AB':'Y_mag', 'J_MAG_AB':'J_mag',
       'H_MAG_AB':'H_mag', 'K_MAG_AB':'K_mag','ch1_mag':'W1mag','ch2_mag':'W2mag'},inplace = True)

In [33]:
f_s = pd.concat([spies_c,first_c])

In [34]:
f_s_c = f_s.drop(columns = ['Y_mag','H_mag','Jmag', 'Hmag', 'Kmag','ext_flg','r_2mass',
                   'zsp', 'f_zsp', 'zph', 'avg_zph','pmRA', 'pmDE', 'angDist_x','fpeak_u','fint_u','rmag','gmag'])

In [35]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [36]:
f_s_c.describe()

,counter,G_mag,R_mag,J_mag,K_mag,W1mag,W2mag,gj,rj,jk,...,objID,mode,class_x,flags,ObsDate,Q,umag,imag,zmag,SpObjID
count,231.00000,440.00000,440.00000,429.00000,440.00000,440.00000,440.00000,231.00000,231.00000,231.00000,...,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000
mean,121.18182,22.79925,21.51493,19.06353,17.50228,16.66543,16.12041,3.29813,1.94598,1.10053,...,1237659168395882752.00000,1.64091,3.47727,1906697916076378.75000,2002.51380,2.77273,23.82290,20.53539,19.96456,109393960844698272.00000
std,70.66936,0.95655,0.94111,0.77973,1.19416,1.79079,2.24580,0.46682,0.41108,0.28857,...,6168163225937.60156,0.48028,1.09853,14063532886316578.00000,1.84952,0.58701,1.24549,0.82975,0.87924,805305094907043200.00000
min,2.00000,19.74073,18.63284,16.25200,13.39000,11.74400,10.64500,2.04061,1.50050,0.70346,...,1237645877943140608.00000,1.00000,3.00000,268435456.00000,1998.71670,1.00000,18.76600,18.00600,17.28900,0.00000
25%,59.50000,22.36024,21.16245,18.61700,16.50825,15.11200,14.19950,3.01728,1.65206,0.93771,...,1237654669069369600.00000,1.00000,3.00000,68987912960.00000,2001.14550,3.00000,22.91175,20.10075,19.55550,0.00000
50%,119.00000,22.87865,21.53590,19.21418,17.89172,16.97293,16.41712,3.26518,1.80920,1.05923,...,1237660224772342272.00000,2.00000,3.00000,35253360136208.00000,2002.82905,3.00000,23.71800,20.56200,19.95300,0.00000
75%,182.50000,23.33717,21.97872,19.67212,18.65466,18.35346,18.25728,3.56271,2.09075,1.21497,...,1237663505589715712.00000,2.00000,3.00000,263953926194850.00000,2003.80650,3.00000,24.69475,20.97050,20.33275,0.00000
max,243.00000,29.96000,29.77600,20.57677,18.89981,19.62744,19.59389,5.02965,3.41739,2.93105,...,1237676326577242624.00000,2.00000,6.00000,144238402399764480.00000,2007.88570,3.00000,27.31000,25.41300,28.55000,6170197397114384384.00000

In [37]:
f_s_c.rename(columns = {'umag':'U_mag','imag':'I_mag','zmag':'Z_mag'},inplace = True)

In [38]:
f_s_c = f_s_c[['counter', 'RA', 'DEC', 'U_mag','G_mag', 'R_mag', 'I_mag', 'Z_mag','J_mag', 'K_mag', 'W1mag', 'W2mag','gj', 'rj',
       'jk', 'rk', 'Fpk', 'Hpk', 'redshift', 'specObjID', 'class', 'JNAME',
       'W3mag', 'W4mag', 'cntr', 'cc_flags', 'var_flg',
       'ph_qual', 'angDist', 'objID', 'mode', 'q_mode', 'class_x', 'SDSS12',
       'm_SDSS12', 'flags', 'ObsDate', 'Q',  
       'SpObjID', 'spType', 'spCl', 'subClass', 'data', 'designation',
       'spectrum']]

## Color Features

u,g,r,i,z,j,k, w1,w2

In [39]:
f_s_c['ug'] = f_s_c['U_mag'] - f_s_c['G_mag']
f_s_c['ur'] = f_s_c['U_mag'] - f_s_c['R_mag']
f_s_c['ui'] = f_s_c['U_mag'] - f_s_c['I_mag']
f_s_c['uz'] = f_s_c['U_mag'] - f_s_c['Z_mag']
f_s_c['uj'] = f_s_c['U_mag'] - f_s_c['J_mag']
f_s_c['uk'] = f_s_c['U_mag'] - f_s_c['K_mag']
f_s_c['uw1'] = f_s_c['U_mag'] - f_s_c['W1mag']
f_s_c['uw2'] = f_s_c['U_mag'] - f_s_c['W2mag']

f_s_c['gr'] = f_s_c['G_mag'] - f_s_c['R_mag']
f_s_c['gi'] = f_s_c['G_mag'] - f_s_c['I_mag']
f_s_c['gz'] = f_s_c['G_mag'] - f_s_c['Z_mag']
f_s_c['gj'] = f_s_c['G_mag'] - f_s_c['J_mag']
f_s_c['gk'] = f_s_c['G_mag'] - f_s_c['K_mag']
f_s_c['gw1'] = f_s_c['G_mag'] - f_s_c['W1mag']
f_s_c['gw2'] = f_s_c['G_mag'] - f_s_c['W2mag']

f_s_c['ri'] = f_s_c['R_mag'] - f_s_c['I_mag']
f_s_c['rz'] = f_s_c['R_mag'] - f_s_c['Z_mag']
f_s_c['rj'] = f_s_c['R_mag'] - f_s_c['J_mag']
f_s_c['rk'] = f_s_c['R_mag'] - f_s_c['K_mag']
f_s_c['rw1'] = f_s_c['R_mag'] - f_s_c['W1mag']
f_s_c['rw2'] = f_s_c['R_mag'] - f_s_c['W2mag']

f_s_c['iz'] = f_s_c['I_mag'] - f_s_c['Z_mag']
f_s_c['ij'] = f_s_c['I_mag'] - f_s_c['J_mag']
f_s_c['ik'] = f_s_c['I_mag'] - f_s_c['K_mag']
f_s_c['iw1'] = f_s_c['I_mag'] - f_s_c['W1mag']
f_s_c['iw2'] = f_s_c['I_mag'] - f_s_c['W2mag']


f_s_c['zj'] = f_s_c['Z_mag'] - f_s_c['J_mag']
f_s_c['zk'] = f_s_c['Z_mag'] - f_s_c['K_mag']
f_s_c['zw1'] = f_s_c['Z_mag'] - f_s_c['W1mag']
f_s_c['zw2'] = f_s_c['Z_mag'] - f_s_c['W2mag']


f_s_c['jk'] = f_s_c['J_mag'] - f_s_c['K_mag']
f_s_c['jw1'] = f_s_c['J_mag'] - f_s_c['W1mag']
f_s_c['jw2'] = f_s_c['J_mag'] - f_s_c['W2mag']

f_s_c['kw1'] = f_s_c['K_mag'] - f_s_c['W1mag']
f_s_c['kw2'] = f_s_c['K_mag'] - f_s_c['W2mag']


f_s_c['w1w2'] = f_s_c['W1mag'] - f_s_c['W2mag']

In [44]:
f_s_c.columns

Index(['counter', 'RA', 'DEC', 'U_mag', 'G_mag', 'R_mag', 'I_mag', 'Z_mag',
       'J_mag', 'K_mag', 'W1mag', 'W2mag', 'gj', 'rj', 'jk', 'rk', 'Fpk',
       'Hpk', 'redshift', 'specObjID', 'class', 'JNAME', 'W3mag', 'W4mag',
       'cntr', 'cc_flags', 'var_flg', 'ph_qual', 'angDist', 'objID', 'mode',
       'q_mode', 'class_x', 'SDSS12', 'm_SDSS12', 'flags', 'ObsDate', 'Q',
       'SpObjID', 'spType', 'spCl', 'subClass', 'data', 'designation',
       'spectrum', 'ug', 'ur', 'ui', 'uz', 'uj', 'uk', 'uw1', 'uw2', 'gr',
       'gi', 'gz', 'gk', 'gw1', 'gw2', 'ri', 'rz', 'rw1', 'rw2', 'iz', 'ij',
       'ik', 'iw1', 'iw2', 'zj', 'zk', 'zw1', 'zw2', 'jw1', 'jw2', 'kw1',
       'kw2', 'w1w2', 'class_cleaned'],
      dtype='object')

In [40]:
class_cleaned = []
for i in f_s_c['class']:
    if i == 'QSO' or i == 'QSO?' or i == 'QSO??':
        class_cleaned.append('QSO')
    elif i =='?' or i =='??':
        class_cleaned.append('?')
    else:
        class_cleaned.append(i)
        
f_s_c['class_cleaned'] = class_cleaned

In [46]:
feature_cleaned = f_s_c[['data','RA', 'DEC', 'G_mag', 'R_mag', 'J_mag', 'K_mag','redshift','class','U_mag', 'I_mag', 'Z_mag','ug', 'ur', 'ui', 'uz', 'uj', 'uk', 'uw1', 'uw2', 'gr',
       'gi', 'gz', 'gk', 'gw1', 'gw2', 'ri', 'rz', 'rw1', 'rw2', 'iz', 'ij',
       'ik', 'iw1', 'iw2', 'zj', 'zk', 'zw1', 'zw2', 'jw1', 'jw2', 'kw1',
       'kw2', 'w1w2',
       'class_cleaned']]

In [47]:
f_s_c[f_s_c['class_cleaned'] == 'no_obs'].describe()

,counter,U_mag,G_mag,R_mag,I_mag,Z_mag,J_mag,K_mag,W1mag,W2mag,...,iw2,zj,zk,zw1,zw2,jw1,jw2,kw1,kw2,w1w2
count,0.00000,124.00000,124.00000,124.00000,124.00000,124.00000,117.00000,124.00000,124.00000,124.00000,...,124.00000,117.00000,124.00000,124.00000,124.00000,117.00000,117.00000,124.00000,124.00000,124.00000
mean,NaN,23.54956,22.50554,21.19808,20.30258,19.79479,18.43012,16.48181,15.20267,14.33979,...,5.96279,1.30740,3.31298,4.59212,5.45500,3.21841,4.06503,1.27914,2.14202,0.86288
std,NaN,1.25484,1.30739,1.32377,0.94651,0.96500,0.52056,0.47886,0.56759,0.72844,...,1.20418,0.76740,0.82649,1.01432,1.20704,0.56059,0.76298,0.44556,0.66293,0.32200
min,NaN,21.41500,20.05700,18.87900,18.30400,17.81000,16.90300,14.75200,13.45900,12.31400,...,4.07100,0.24700,2.18200,2.91800,3.59300,1.87600,2.55100,0.10300,0.77800,0.50100
25%,NaN,22.59100,21.57639,20.29500,19.67425,19.28400,18.18600,16.20875,14.82375,13.76750,...,4.93350,0.79100,2.75725,3.86625,4.46800,2.80500,3.50100,0.94500,1.64325,0.61100
50%,NaN,23.32250,22.43311,21.26700,20.38150,19.79300,18.59600,16.58750,15.25400,14.45800,...,5.86600,1.16900,3.14750,4.39550,5.26950,3.18000,3.98500,1.28900,2.03500,0.71500
75%,NaN,24.35725,23.34492,22.07903,20.89825,20.26100,18.80100,16.87750,15.59875,14.90900,...,6.70700,1.53600,3.64750,5.13000,6.23675,3.54500,4.44600,1.57500,2.47525,1.10325
max,NaN,27.31000,29.96000,29.77600,23.18100,22.82700,19.19800,16.99200,16.87800,16.20300,...,9.41800,5.16100,7.06000,7.88300,9.27600,4.89300,6.46200,2.70800,4.27700,1.77400

In [48]:
feature_cleaned[feature_cleaned['class_cleaned'] == 'no_obs']

,data,RA,DEC,G_mag,R_mag,J_mag,K_mag,redshift,class,U_mag,...,zj,zk,zw1,zw2,jw1,jw2,kw1,kw2,w1w2,class_cleaned
0,FIRST,135.05818,5.59699,23.34100,21.67100,18.86600,16.68300,0.00000,no_obs,26.72100,...,1.05900,3.24200,4.64300,5.45100,3.58400,4.39200,1.40100,2.20900,0.80800,no_obs
1,FIRST,135.44687,4.43296,21.56600,20.28600,18.34600,16.49600,0.00000,no_obs,23.86600,...,0.93500,2.78500,3.30500,4.04200,2.37000,3.10700,0.52000,1.25700,0.73700,no_obs
3,FIRST,136.03940,-0.12321,22.62600,21.56700,18.61300,16.52000,0.00000,no_obs,24.38300,...,1.71600,3.80900,4.98800,6.26300,3.27200,4.54700,1.17900,2.45400,1.27500,no_obs
5,FIRST,137.83102,9.65900,22.80800,21.53100,18.76000,16.89100,0.00000,no_obs,23.44600,...,0.72000,2.58900,4.39500,4.95500,3.67500,4.23500,1.80600,2.36600,0.56000,no_obs
14,FIRST,141.88872,6.00699,23.81500,21.53500,18.86700,16.90200,0.00000,no_obs,23.58600,...,1.37600,3.34100,4.76900,5.47200,3.39300,4.09600,1.42800,2.13100,0.70300,no_obs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,FIRST,230.85738,1.57425,24.52900,22.31500,18.66300,16.37600,0.00000,no_obs,23.79800,...,2.14000,4.42700,6.18900,7.34500,4.04900,5.20500,1.76200,2.91800,1.15600,no_obs
202,FIRST,231.55827,-1.88645,22.49000,20.96700,18.51500,16.79100,0.00000,no_obs,24.91800,...,1.69900,3.42300,4.43700,5.11800,2.73800,3.41900,1.01400,1.69500,0.68100,no_obs
204,FIRST,232.72763,0.98060,21.70900,20.45700,18.67200,16.20500,0.00000,no_obs,22.92300,...,1.50900,3.97600,5.87500,6.83300,4.36600,5.32400,1.89900,2.85700,0.95800,no_obs
206,FIRST,234.15163,8.96573,21.40300,19.73100,17.96900,16.19700,0.00000,no_obs,25.08100,...,0.64500,2.41700,3.60400,4.20300,2.95900,3.55800,1.18700,1.78600,0.59900,no_obs
208,FIRST,234.92323,-1.35383,20.95300,19.71800,17.55900,15.48100,0.00000,no_obs,23.90300,...,1.16800,3.24600,4.65300,5.48400,3.48500,4.31600,1.40700,2.23800,0.83100,no_obs

In [50]:
f_s_c.to_csv('../data/features.csv')
feature_cleaned.to_csv('../data/feature_cleaned.csv')