In [20]:
import pandas as pd
import numpy as np

## Data Clean and Concat

In [21]:
first = pd.read_csv('../data/combined/FIRST_WISE_SDSS_DR12.csv')
spies = pd.read_csv('../data/combined/SpIES_WISE_SDSS_DR12.csv')
red_q = pd.read_csv('../data/red_qso.csv')

In [22]:
first['data'] = 'FIRST'
spies['data'] = 'SpIES'

In [23]:
first_c = first.drop(columns = ['errHalfMaj',
       'errHalfMin', 'errPosAng','errHalfMaj_x', 'errHalfMin_x', 'errPosAng_x',
                      'e_umag','e_gmag','e_rmag','e_imag','e_zmag','e_zsp', 'e_zph',
                     'e_pmRA','e_pmDE','RAdeg', 'DEdeg'])

spies_c = spies.drop(columns = ['ra_x',
       'dec_x', 'errHalfMaj', 'errHalfMin', 'errPosAng','e_W1mag', 'e_W2mag',
       'e_W3mag', 'e_W4mag', 'e_Jmag', 'e_Hmag', 'e_Kmag','RAdeg', 'DEdeg',
       'errHalfMaj_x', 'errHalfMin_x', 'errPosAng_x', 'e_umag','e_gmag','e_rmag','e_imag','e_zmag','e_zsp', 'e_zph',
                     'e_pmRA','e_pmDE'])

In [24]:
first_c.rename(columns ={'ra_u':'RA','dec_u':'DEC','Jmag':'J_mag','Kmag':'K_mag','Class':'class'},inplace = True)

In [25]:
spies_c.rename(columns = {'G_MAG_AB':'G_mag','R_MAG_AB':'R_mag', 'Y_MAG_AB':'Y_mag', 'J_MAG_AB':'J_mag',
       'H_MAG_AB':'H_mag', 'K_MAG_AB':'K_mag'},inplace = True)

In [26]:
f_s = pd.concat([spies_c,first_c])

In [27]:
f_s_c = f_s.drop(columns = ['Y_mag','H_mag','ch1_mag','ch2_mag','Jmag', 'Hmag', 'Kmag','ext_flg','r_2mass',
                   'zsp', 'f_zsp', 'zph', 'avg_zph','pmRA', 'pmDE', 'angDist_x','fpeak_u','fint_u','rmag','gmag'])

In [28]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [29]:
f_s_c.describe()

,counter,G_mag,R_mag,J_mag,K_mag,gj,rj,jk,rk,Fpk,...,objID,mode,class_x,flags,ObsDate,Q,umag,imag,zmag,SpObjID
count,231.00000,440.00000,440.00000,429.00000,440.00000,231.00000,231.00000,231.00000,231.00000,231.00000,...,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000,440.00000
mean,121.18182,22.79925,21.51493,19.06353,17.50228,3.29813,1.94598,1.10053,3.04652,-941.74442,...,1237659168395882752.00000,1.64091,3.47727,1906697916076381.75000,2002.51380,2.77273,23.82290,20.53539,19.96456,109393960844698272.00000
std,70.66936,0.95655,0.94111,0.77973,1.19416,0.46682,0.41108,0.28857,0.50743,235.07208,...,6168163225937.60449,0.48028,1.09853,14063532886316578.00000,1.84952,0.58701,1.24549,0.82975,0.87924,805305094907043840.00000
min,2.00000,19.74073,18.63284,16.25200,13.39000,2.04061,1.50050,0.70346,2.60193,-999.00000,...,1237645877943140608.00000,1.00000,3.00000,268435456.00000,1998.71670,1.00000,18.76600,18.00600,17.28900,0.00000
25%,59.50000,22.36024,21.16245,18.61700,16.50825,3.01728,1.65206,0.93771,2.70737,-999.00000,...,1237654669069369856.00000,1.00000,3.00000,68987912960.00000,2001.14550,3.00000,22.91175,20.10075,19.55550,0.00000
50%,119.00000,22.87865,21.53590,19.21418,17.89172,3.26518,1.80920,1.05923,2.84656,-999.00000,...,1237660224772342272.00000,2.00000,3.00000,35253360136208.00000,2002.82905,3.00000,23.71800,20.56200,19.95300,0.00000
75%,182.50000,23.33717,21.97872,19.67212,18.65466,3.56271,2.09075,1.21497,3.19364,-999.00000,...,1237663505589715456.00000,2.00000,3.00000,263953926194850.00000,2003.80650,3.00000,24.69475,20.97050,20.33275,0.00000
max,243.00000,29.96000,29.77600,20.57677,18.89980,5.02965,3.41739,2.93105,5.00777,95.87000,...,1237676326577242624.00000,2.00000,6.00000,144238402399764480.00000,2007.88570,3.00000,27.31000,25.41300,28.55000,6170197397114384384.00000

In [30]:
f_s_c.rename(columns = {'umag':'U_mag','imag':'I_mag','zmag':'Z_mag'},inplace = True)

In [31]:
f_s_c = pd.concat([f_s_c,red_q])

In [32]:
f_s_c['gj'] = f_s_c['G_mag'] - f_s_c['J_mag']
f_s_c['gr'] = f_s_c['G_mag'] - f_s_c['R_mag']
f_s_c['gk'] = f_s_c['G_mag'] - f_s_c['K_mag']
f_s_c['gu'] = f_s_c['G_mag'] - f_s_c['U_mag']
f_s_c['gi'] = f_s_c['G_mag'] - f_s_c['I_mag']
f_s_c['gz'] = f_s_c['G_mag'] - f_s_c['Z_mag']

f_s_c['jr'] = f_s_c['J_mag'] - f_s_c['R_mag']
f_s_c['jk'] = f_s_c['J_mag'] - f_s_c['K_mag']
f_s_c['ju'] = f_s_c['J_mag'] - f_s_c['U_mag']
f_s_c['ji'] = f_s_c['J_mag'] - f_s_c['I_mag']
f_s_c['jz'] = f_s_c['J_mag'] - f_s_c['Z_mag']

f_s_c['rk'] = f_s_c['R_mag'] - f_s_c['K_mag']
f_s_c['ru'] = f_s_c['R_mag'] - f_s_c['U_mag']
f_s_c['ri'] = f_s_c['R_mag'] - f_s_c['I_mag']
f_s_c['rz'] = f_s_c['R_mag'] - f_s_c['Z_mag']

f_s_c['ku'] = f_s_c['K_mag'] - f_s_c['U_mag']
f_s_c['ki'] = f_s_c['K_mag'] - f_s_c['I_mag']
f_s_c['kz'] = f_s_c['K_mag'] - f_s_c['Z_mag']

f_s_c['ui'] = f_s_c['U_mag'] - f_s_c['I_mag']
f_s_c['uz'] = f_s_c['U_mag'] - f_s_c['Z_mag']

f_s_c['iz'] = f_s_c['I_mag'] - f_s_c['Z_mag']

f_s_c['w1w2'] = f_s_c['W1mag'] - f_s_c['W2mag']

In [33]:
class_cleaned = []
for i in f_s_c['class']:
    if i == 'QSO' or i == 'QSO?' or i == 'QSO??' or i == 'redQSO':
        class_cleaned.append('QSO')
    elif i =='?' or i =='??':
        class_cleaned.append('?')
    else:
        class_cleaned.append(i)
        
f_s_c['class_cleaned'] = class_cleaned

In [34]:
feature_cleaned = f_s_c[['data','RA', 'DEC', 'G_mag', 'R_mag', 'J_mag', 'K_mag','redshift','class','U_mag', 'I_mag', 'Z_mag','gr', 'gk', 'gu', 'gi', 'gz', 'jr', 'ju', 'ji', 'jz', 'ru',
       'ri', 'rz', 'ku', 'ki', 'kz', 'ui', 'uz', 'iz', 'w1w2',
       'class_cleaned']]

In [35]:
f_s_c[f_s_c['class_cleaned'] == 'no_obs'].describe()

,counter,G_mag,R_mag,J_mag,K_mag,gj,rj,jk,rk,Fpk,...,ru,ri,rz,ku,ki,kz,ui,uz,iz,w1w2
count,0.00000,124.00000,124.00000,117.00000,124.00000,117.00000,0.00000,117.00000,124.00000,0.00000,...,124.00000,124.00000,124.00000,124.00000,124.00000,124.00000,124.00000,124.00000,124.00000,124.00000
mean,nan,22.50554,21.19808,18.43012,16.48181,4.03699,nan,1.96836,4.71627,nan,...,-2.35148,0.89550,1.40329,-7.06775,-3.82077,-3.31298,3.24698,3.75477,0.50779,0.86288
std,nan,1.30739,1.32377,0.52056,0.47886,1.13716,nan,0.22404,1.19637,nan,...,1.30966,0.92188,1.06283,1.19803,0.77452,0.82649,1.28622,1.38549,0.40756,0.32200
min,nan,20.05700,18.87900,16.90300,14.75200,2.72300,nan,1.51800,3.25400,nan,...,-5.58200,-0.71600,-0.51200,-11.66800,-6.84100,-7.06000,0.10900,-0.11000,-1.16300,0.50100
25%,nan,21.57639,20.29500,18.18600,16.20875,3.35000,nan,1.79700,3.95100,nan,...,-3.27566,0.57950,0.98600,-7.79650,-4.24825,-3.64750,2.43600,2.83250,0.39125,0.61100
50%,nan,22.43311,21.26700,18.59600,16.58750,3.78000,nan,1.92200,4.47900,nan,...,-2.38450,0.69750,1.24000,-6.88200,-3.67300,-3.14750,3.15300,3.66250,0.51600,0.71500
75%,nan,23.34492,22.07903,18.80100,16.87750,4.44093,nan,2.09300,5.31937,nan,...,-1.52575,1.08742,1.78286,-6.16625,-3.26900,-2.75725,4.13700,4.55200,0.69025,1.10325
max,nan,29.96000,29.77600,19.19800,16.99200,12.48100,nan,2.58700,14.13400,nan,...,2.46600,9.77400,11.23700,-4.99500,-2.62800,-2.18200,7.30800,8.77100,1.85400,1.77400

In [36]:
feature_cleaned[feature_cleaned['class_cleaned'] == 'no_obs']

,data,RA,DEC,G_mag,R_mag,J_mag,K_mag,redshift,class,U_mag,...,ri,rz,ku,ki,kz,ui,uz,iz,w1w2,class_cleaned
0,FIRST,135.05818,5.59699,23.34100,21.67100,18.86600,16.68300,0.00000,no_obs,26.72100,...,0.77400,1.74600,-10.03800,-4.21400,-3.24200,5.82400,6.79600,0.97200,0.80800,no_obs
1,FIRST,135.44687,4.43296,21.56600,20.28600,18.34600,16.49600,0.00000,no_obs,23.86600,...,0.37900,1.00500,-7.37000,-3.41100,-2.78500,3.95900,4.58500,0.62600,0.73700,no_obs
3,FIRST,136.03940,-0.12321,22.62600,21.56700,18.61300,16.52000,0.00000,no_obs,24.38300,...,0.45700,1.23800,-7.86300,-4.59000,-3.80900,3.27300,4.05400,0.78100,1.27500,no_obs
5,FIRST,137.83102,9.65900,22.80800,21.53100,18.76000,16.89100,0.00000,no_obs,23.44600,...,1.12400,2.05100,-6.55500,-3.51600,-2.58900,3.03900,3.96600,0.92700,0.56000,no_obs
14,FIRST,141.88872,6.00699,23.81500,21.53500,18.86700,16.90200,0.00000,no_obs,23.58600,...,0.68000,1.29200,-6.68400,-3.95300,-3.34100,2.73100,3.34300,0.61200,0.70300,no_obs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,FIRST,230.85738,1.57425,24.52900,22.31500,18.66300,16.37600,0.00000,no_obs,23.79800,...,0.70400,1.51200,-7.42200,-5.23500,-4.42700,2.18700,2.99500,0.80800,1.15600,no_obs
202,FIRST,231.55827,-1.88645,22.49000,20.96700,18.51500,16.79100,0.00000,no_obs,24.91800,...,0.54200,0.75300,-8.12700,-3.63400,-3.42300,4.49300,4.70400,0.21100,0.68100,no_obs
204,FIRST,232.72763,0.98060,21.70900,20.45700,18.67200,16.20500,0.00000,no_obs,22.92300,...,0.00900,0.27600,-6.71800,-4.24300,-3.97600,2.47500,2.74200,0.26700,0.95800,no_obs
206,FIRST,234.15163,8.96573,21.40300,19.73100,17.96900,16.19700,0.00000,no_obs,25.08100,...,0.71100,1.11700,-8.88400,-2.82300,-2.41700,6.06100,6.46700,0.40600,0.59900,no_obs
208,FIRST,234.92323,-1.35383,20.95300,19.71800,17.55900,15.48100,0.00000,no_obs,23.90300,...,0.53800,0.99100,-8.42200,-3.69900,-3.24600,4.72300,5.17600,0.45300,0.83100,no_obs

In [37]:
f_s_c.to_csv('../data/features.csv')
feature_cleaned.to_csv('../data/feature_cleaned.csv')